"use client";
import React from "react";
import styles from "./reportComponent.module.css";
import { Download, Filter } from "lucide-react";

export default function ReportsComponent() {
  return (
    <main className={styles.main}>
      {/* === Filters Section === */}
      <section className={styles.filterSection}>
        <div className={styles.filterGroup}>
          <label>Date Range</label>
          <input type="date" className={styles.input} />
          <span>to</span>
          <input type="date" className={styles.input} />
        </div>

        <div className={styles.filterGroup}>
          <label>Report Type</label>
          <select className={styles.input}>
            <option>All</option>
            <option>Search Reports</option>
            <option>Batch Screening</option>
            <option>Positive Matches</option>
            <option>Audit Logs</option>
          </select>
        </div>

        <button className={styles.filterBtn}>
          <Filter className="w-4 h-4 mr-1" /> Apply
        </button>
      </section>

      {/* === Reports Table === */}
      <section className={styles.tableSection}>
        <div className={styles.tableHeader}>
          <h3>Generated Reports</h3>
          <button className={styles.downloadBtn}>
            <Download className="w-4 h-4 mr-2" /> Export CSV
          </button>
        </div>

        <table className={styles.table}>
          <thead>
            <tr>
              <th>Report Name</th>
              <th>Type</th>
              <th>Generated By</th>
              <th>Date</th>
              <th>Status</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>Weekly Sanctions Report</td>
              <td>Search Report</td>
              <td>Admin</td>
              <td>Nov 3, 2025</td>
              <td>
                <span className={styles.statusSuccess}>Completed</span>
              </td>
              <td>
                <a href="#" className={styles.link}>
                  Download
                </a>
              </td>
            </tr>
            <tr>
              <td>Batch Screening Log #241</td>
              <td>Batch Screening</td>
              <td>Sarah M.</td>
              <td>Nov 2, 2025</td>
              <td>
                <span className={styles.statusWarning}>In Progress</span>
              </td>
              <td>
                <a href="#" className={styles.link}>
                  View
                </a>
              </td>
            </tr>
            <tr>
              <td>October Audit Summary</td>
              <td>Audit Log</td>
              <td>Compliance Team</td>
              <td>Nov 1, 2025</td>
              <td>
                <span className={styles.statusSuccess}>Completed</span>
              </td>
              <td>
                <a href="#" className={styles.link}>
                  Download
                </a>
              </td>
            </tr>
          </tbody>
        </table>
      </section>

      {/* === Summary Cards === */}
      <section className={styles.summaryGrid}>
        <div className={styles.summaryCard}>
          <p>Total Reports Generated</p>
          <h2>126</h2>
        </div>
        <div className={`${styles.summaryCard} ${styles.green}`}>
          <p>Completed</p>
          <h2>118</h2>
        </div>
        <div className={`${styles.summaryCard} ${styles.yellow}`}>
          <p>In Progress</p>
          <h2>8</h2>
        </div>
      </section>
    </main>
  );
}
